### ISSUE TITLE
Closing tabs other than the 1st, not the active one

### ISSUE THREAD

**Issue by pmichna** [smockle/close-other-tabs#2]
When I use the plugin and `alt-cmd-w` it closes all the tabs apart from the first one from the left instead of all the tabs apart from the active one.

**Comment by smockle** [comment]
Thanks for reporting this @pmichna. I cannot reproduce this issue locally. Could you please provide additional information about your local installation?

Specifically, can you provide your Atom version number, your close-other-tabs version number, a list of other packages installed in Atom, and any custom keybindings you’ve defined (Atom > Keymap...)?

**Comment by pmichna** [comment]
Steps to reproduce:
1. Open a few tabs, let's say `A`, `B`, `C` and `D` (in that order).
2. Activate (focus) tab `B`.
3. `alt-cmd-w`
4. Tab `B` remains open, `A`, `C` and `D`are closed which is **fine**.
5. Having `B` still open, open again `A`, `C`, `D`.
6. Activate `A` (which is now 2nd tab from the left).
7. `alt-cmd-w`
8. Tab `B` remains open, `A`, `C` and `D`are closed which is **wrong**.

It seems like after using the combination for the first time, the tab that remains open is afterwards always treated like the active one until you close it.

My specs:
- Atom version: 1.11.2
- close-other-tabs version: 0.1.0
- list of packages other than the core ones:
  - close-other-tabs
  - git-blame
  - highlight-selected
  - language-slim
- custom keybindings:

```
'atom-workspace':
  'shift-cmd-W': 'close-other-tabs:close-other-tabs'
```

Right, I actually use `shift-cmd-W` instead instead of `alt-cmd-w`, so I lied a little in the steps to reproduce. :) However, I guess it has nothing to do with the problem.

**Comment by pmichna** [comment]
Hey @smockle, have you managed to reproduce the problem?

**Comment by smockle** [comment]
@pmichna I apologize for the delay! I was able to reproduce the issue—thank you for providing such detailed and easy-to-follow instructions.

I attribute the issue to a lingering `right-clicked` class. A related bug occurs when you have two open tabs (`A` and `B`) and `B` is active:
1. Right-click `A` (a context menu will appear, and `B` should still be active)
2. Close the context menu without selecting an option
3. Press <kbd>option</kbd><kbd>command</kbd><kbd>w</kbd>

You’d expect `B` (the active tab) to close, but actually `A` closes—because it has a `right-clicked` class.

I believe I’ve fixed both issues in [v0.1.1](https://atom.io/packages/close-other-tabs). Could you please update to that version and see if you can reproduce this issue?

**Comment by pmichna** [comment]
Thanks @smockle. I've updated the package and the problem disappeared. Good job! 👍

**Comment by smockle** [comment]
@pmichna Excellent! Thanks again for reporting this. 🎉
